apiVersion: v1
kind: Service
metadata:
  name: ai-grading-service
  labels:
    app: ai-grading-app
spec:
  selector:
    app: ai-grading-app # This must match the labels in your Deployment's template
  ports:
    - protocol: TCP
      port: 80       # The port the service will be available on externally (within the cluster or via LoadBalancer)
      targetPort: 5000 # The port your Flask application container is listening on
  # Type of service. Common types:
  # ClusterIP: Exposes the service on an internal IP in the cluster. Default type.
  # NodePort: Exposes the service on each Node's IP at a static port.
  # LoadBalancer: Creates an external load balancer in cloud environments (e.g., AWS ELB, GCP Cloud Load Balancer).
  # ExternalName: Maps the service to an external name (e.g., foo.bar.example.com), by returning a CNAME record.
  type: LoadBalancer # Change to NodePort or ClusterIP if not using a cloud provider with LoadBalancer support
